on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  PROJECT_NAME: Aspire.Hosting.Bun

jobs:
  semantic-release:
    name: Create a Package Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.x
      - name: Restore dependencies
        run: dotnet restore ./${{ env.PROJECT_NAME }}.sln
      - name: Setup git version
        uses: gittools/actions/gitversion/setup@v3.0.0
        with:
          versionSpec: '6.x'
      - name: Bump version and push tag
        id: tag_version
        uses: gittools/actions/gitversion/execute@v3.0.0
        with:
          updateAssemblyInfo: true
      - name: Create a GitHub release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ steps.tag_version.outputs.MajorMinorPatch }}
          name: Release ${{ steps.tag_version.outputs.MajorMinorPatch }}
      - name: Create NuGet Package
        run: dotnet build -c Release ./${{ env.PROJECT_NAME }}.sln && dotnet pack -c Release -p:PackageVersion=${{ steps.tag_version.outputs.MajorMinorPatch }} -o . ./${{ env.PROJECT_NAME }}.sln
      - name: Upload Package for Publishing
        uses: actions/upload-artifact@v4
        with:
          name: PackedLib
          path: ./*.nupkg

  github-publish:
    needs: semantic-release
    name: Publish to GitHub
    runs-on: ubuntu-latest
    steps:
      - name: Download built project
        uses: actions/download-artifact@v4
        with:
          name: PackedLib
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.x # Match the version used in semantic-release
      - name: Push Package to GitHub
        run: dotnet nuget push --api-key ${{ secrets.GITHUB_TOKEN }} --source "https://nuget.pkg.github.com/ru1t3rl/index.json" *.nupkg
